#include "test_util.h"

#include <filesystem>

using namespace clxcpp;

static std::string data_dir() { return CLXCPP_TEST_DATA_DIR; }
static std::string ref_dir() { return CLXCPP_TEST_REFERENCE_DIR; }

// The reference files were generated by the Python implementation with the
// relative path "tests/data/<key>.clx", so summaries/JSON embed that path.
static std::string rel_path(const std::string& key) {
  return "tests/data/" + key + ".clx";
}

TEST(parity_summary_samp1) {
  std::string key = "Samp1_20260804_161544_00.06.946";
  auto bytes = read_file_bytes(data_dir() + "/" + key + ".clx");
  clx_file f = parse(bytes, rel_path(key));
  std::string expect = read_file_text(ref_dir() + "/" + key + ".summary.txt");
  CHECK_EQ(f.summary() + "\n", expect);
}

TEST(parity_summary_samp2) {
  std::string key = "Samp2_20260717_194348_00.00.332";
  auto bytes = read_file_bytes(data_dir() + "/" + key + ".clx");
  clx_file f = parse(bytes, rel_path(key));
  std::string expect = read_file_text(ref_dir() + "/" + key + ".summary.txt");
  CHECK_EQ(f.summary() + "\n", expect);
}

TEST(parity_metadata_json_samp1) {
  std::string key = "Samp1_20260804_161544_00.06.946";
  auto bytes = read_file_bytes(data_dir() + "/" + key + ".clx");
  clx_file f = parse(bytes, rel_path(key));
  std::string expect = read_file_text(ref_dir() + "/" + key + ".metadata.json");
  CHECK_EQ(f.to_json(), expect);
}

TEST(parity_metadata_json_samp2) {
  std::string key = "Samp2_20260717_194348_00.00.332";
  auto bytes = read_file_bytes(data_dir() + "/" + key + ".clx");
  clx_file f = parse(bytes, rel_path(key));
  std::string expect = read_file_text(ref_dir() + "/" + key + ".metadata.json");
  CHECK_EQ(f.to_json(), expect);
}

TEST(parity_16bit_png_pixels) {
  // Compare decompressed pixels of our 16-bit PNG against the Python-generated
  // reference PNG (deflate streams differ between zlib and miniz, so compare
  // decoded pixel data, not raw bytes).
  for (auto key : {"Samp1_20260804_161544_00.06.946",
                   "Samp2_20260717_194348_00.00.332"}) {
    clx_file f = load(data_dir() + "/" + key + ".clx");
    for (std::size_t i = 0; i < f.images.size(); ++i) {
      auto mine = f.images[i].to_png_bytes();
      auto ref = read_file_bytes(ref_dir() + "/" + key + "_" +
                                 std::to_string(i) + "_16bit.png");
      auto dm = decode_png(mine);
      auto dr = decode_png(ref);
      CHECK_EQ(dm.width, dr.width);
      CHECK_EQ(dm.height, dr.height);
      CHECK_EQ(dm.bits, dr.bits);
      CHECK_EQ(dm.pixels_le, dr.pixels_le);
    }
  }
}

TEST(parity_preview_png_pixels) {
  for (auto key : {"Samp1_20260804_161544_00.06.946",
                   "Samp2_20260717_194348_00.00.332"}) {
    clx_file f = load(data_dir() + "/" + key + ".clx");
    for (std::size_t i = 0; i < f.images.size(); ++i) {
      auto mine = f.images[i].preview_png_bytes();
      auto ref = read_file_bytes(ref_dir() + "/" + key + "_" +
                                 std::to_string(i) + "_preview.png");
      auto dm = decode_png(mine);
      auto dr = decode_png(ref);
      CHECK_EQ(dm.width, dr.width);
      CHECK_EQ(dm.height, dr.height);
      CHECK_EQ(dm.bits, dr.bits);
      CHECK_EQ(dm.pixels_le, dr.pixels_le);
    }
  }
}

TEST(export_writes_instrument_naming) {
  std::string key = "Samp1_20260804_161544_00.06.946";
  auto bytes = read_file_bytes(data_dir() + "/" + key + ".clx");
  clx_file f = parse(bytes, rel_path(key));

  std::filesystem::path tmp =
      std::filesystem::temp_directory_path() / "clxcpp_export_test";
  std::filesystem::remove_all(tmp);

  auto written = export_images(f, tmp.string(), {"tiff", "png", "json"});
  CHECK_EQ(written.size(), (std::size_t)5);  // 2x tiff + 2x png + json

  std::vector<std::string> expected = {
      (tmp / "Samp1_20260804_161544_00.06.946_0_16bit.tif").string(),
      (tmp / "Samp1_20260804_161544_00.06.946_0_16bit.png").string(),
      (tmp / "Samp1_20260804_161544_00.06.946_1_16bit.tif").string(),
      (tmp / "Samp1_20260804_161544_00.06.946_1_16bit.png").string(),
      (tmp / "Samp1_20260804_161544_00.06.946_metadata.json").string(),
  };
  CHECK_EQ(written, expected);
  for (auto& p : expected) CHECK(std::filesystem::exists(p));

  std::filesystem::remove_all(tmp);
}

TEST(export_unknown_format_raises) {
  std::string key = "Samp1_20260804_161544_00.06.946";
  auto bytes = read_file_bytes(data_dir() + "/" + key + ".clx");
  clx_file f = parse(bytes, rel_path(key));
  bool threw = false;
  try {
    export_images(f, "out", {"gif"});
  } catch (const std::invalid_argument&) {
    threw = true;
  }
  CHECK(threw);
}
